version: '3'

services:
  competitive_bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      .env
    environment:
      API: ${API}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    depends_on:
      - dj-mariadb
      - dj-domserver

  dj-mariadb:
    image: docker.io/mariadb
    hostname: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=domjudge
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
    ports:
      - 13306:3306
    command: --max-connections=1000 --max-allowed-packet=512M
    volumes:
      - /var/lib/mysql

  dj-domserver:
    image: docker.io/domjudge/domserver
    hostname: domserver
    environment:
      - MYSQL_ROOT_PASSWORD=domjudge
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=djpw
      - MYSQL_DATABASE=domjudge
      - MYSQL_HOST=mariadb
    ports:
      - 12345:80
    links:
      - dj-mariadb:mariadb

#  dj-judgehost:
#    image: domjudge/judgehost
#    privileged: true
#    hostname: judgedaemon-0
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    environment:
#      - DAEMON_ID=0
#      - JUDGEDAEMON_PASSWORD=domjudge
#    links:
#      - dj-domserver:domserver
