version: '3'

services:
  competitive_bot:
    container_name: competitive_bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      .env

  dj-mariadb:
    container_name: cb-mariadb
    image: docker.io/mariadb
    restart: always
    hostname: mariadb
    env_file:
      .env
    ports:
      - 13306:3306
    command: --max-connections=1000 --max-allowed-packet=512M
    volumes:
      - /var/lib/mysql

  dj-domserver:
    container_name: cb-domserver
    image: docker.io/domjudge/domserver
    restart: always
    hostname: domserver
    env_file:
      .env
    ports:
      - 12345:80
    links:
      - dj-mariadb:mariadb

  dj-judgehost:
    container_name: cb-judgehost
    image: domjudge/judgehost
    restart: always
    privileged: true
    hostname: judgedaemon
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    env_file:
      .env
    links:
      - dj-domserver:dj-domserver
